//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_MDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string Descricao { get; set; }
        public int id_paciente { get; set; }
        public int id_medico { get; set; }
        public int id_rececionista { get; set; }
    
        public virtual Médico Médico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Rececionista Rececionista { get; set; }
    }
}
