//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_MDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Médico : Utilizador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Médico()
        {
            this.Consultas = new HashSet<Consulta>();
        }
    
        public int id_especialidade { get; set; }
        public string HoraEntrada { get; set; }
        public string HoraSaida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consultas { get; set; }
        public virtual Especialidade Especialidade { get; set; }
    }
}
