//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_MDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizador
    {
        public int Id { get; set; }
        public string N_Contribuinte { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string NºTelemovel { get; set; }
        public string Email { get; set; }
        public System.DateTime DataNascimento { get; set; }
    }
}
